# These are supported funding model platforms

custom: ['https://venmo.com/Jeron-Osguthorpe', 'https://cash.app/$JeronOsguthorpe', 'https://www.paypal.com/donate/?hosted_button_id=R6QT5XCLWMW98', 'https://gofund.me/83201568']# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']

